#!/bin/bash
blue(){
    echo -e "\033[34m\033[01m$1\033[0m"
}
green(){
    echo -e "\033[32m\033[01m$1\033[0m"
}
yellow(){
    echo -e "\033[33m\033[01m$1\033[0m"
}
red(){
    echo -e "\033[31m\033[01m$1\033[0m"
}



realm(){
	wget -N --no-check-certificate https://git.io/realm.sh && chmod +x realm.sh && ./realm.sh
}
Nfg_cn(){
	wget --no-check-certificate -qO natcfg.sh http://www.arloor.com/sh/iptablesUtils/natcfg.sh && bash natcfg.sh
}
Nfg_ab(){
	wget --no-check-certificate -qO natcfg.sh https://raw.githubusercontent.com/arloor/iptablesUtils/master/natcfg.sh && bash natcfg.sh
}
Nfg_u(){
	wget --no-check-certificate -qO uninstall.sh https://raw.githubusercontent.com/arloor/iptablesUtils/master/dnat-uninstall.sh && bash uninstall.sh
}
Brook_D(){
	apt-get install dnsutils -y && sudo apt-get install wget -y && wget https://raw.githubusercontent.com/ECIAP/brook/master/brook-pf-mod.sh && chmod +x brook-pf-mod.sh && bash brook-pf-mod.sh
}
Brook_C(){
	yum install bind-utils -y && yum install wget -y && wget https://raw.githubusercontent.com/ECIAP/brook/master/brook-pf-mod.sh && chmod +x brook-pf-mod.sh && bash brook-pf-mod.sh
}
gost(){
	wget --no-check-certificate -O gost.sh https://raw.githubusercontent.com/KANIKIG/Multi-EasyGost/master/gost.sh && chmod +x gost.sh && ./gost.sh
}


start_menu(){
    clear

	green "===============流媒体检测======================="
	 yellow " 1. realm 中专 "
	 yellow " 2. natcfg 国内鸡 "
	 yellow " 3. natcfg 国外鸡 "
	 yellow " 4. 卸载natcfg "
	 yellow " 5. Brook Debian "
	 yellow " 6. Brook Centos "
	 yellow " 7. gost "

        red " 0. 退出脚本 "
    echo
    read -p "请输入数字:" num
    case "$num" in
    		1) realm ;;
		2) Nfg_cn ;;
		3) Nfg_ab ;;
		4) Nfg_u ;;
		5) Brook_D ;;
		6) Brook_C ;;
		7) gost ;;
		0) exit 0 ;;
		*)
	clear
	echo "请输入正确数字"
	sleep 2s
	start_menu
	;;
    esac
} 

start_menu
